#@TYPE: Machine
#@NAME: Forecr DSBOARD-AGX
#@DESCRIPTION: Forecr DSBOARD-AGX carrier board for the Jetson AGX Orin
# (P3701) module.

MACHINEOVERRIDES =. "forecr:"

require conf/machine/include/agx-orin.inc
require conf/machine/include/p3737.inc

KERNEL_DEVICETREE ?= "tegra234-p3737-0000+p3701-0000-nv.dtb"
TEGRA_BUPGEN_SPECS ?= "fab=300;boardsku=0000;boardrev=;chipsku=00:00:00:D0;bup_type=bl \
                       fab=300;boardsku=0000;boardrev=;bup_type=kernel"

# Board-specific pinmux/padvoltage.
TEGRA_FLASHVAR_PINMUX_CONFIG = "tegra234-forecr-dsboard-agx-pinmux.dtsi"
TEGRA_FLASHVAR_PMC_CONFIG = "tegra234-forecr-dsboard-agx-padvoltage-default.dtsi"
