BBPATH .= ":${LAYERDIR}"
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "forecr"
BBFILE_PATTERN_forecr = "^${LAYERDIR}/"
BBFILE_PRIORITY_forecr = "8"

LAYERVERSION_forecr = "1"

LAYERDEPENDS_forecr = "tegra"

LAYERSERIES_COMPAT_forecr = "wrynose"
